language: android
jdk: oraclejdk8
sudo: required

before_cache:
    -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    -rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    

cache:
    directories:
        -$HOME/.gradle/caches/
        -$HOME/.gradle/wrapper/
        

env:
    global:
        - ANDROID_API=27
        - ANDROID_BUILD_TOOLS=27.0.3


android:
  components:
    - tools
    - platform-tools
    - android-$ANDROID_API
    - build-tools-$ANDROID_BUILD_TOOLS
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    

before_install:
    - chmod +x gradlew
    - ./gradlew dependencies || true
    

script:
    - "./gradlew clean build"


deploy:
    provider: releases
    file: *.apk
    skip_cleanup: true
    
    on:
        repo: nlACh/3DM
        tags: true
        jdk: oraclejdk8
    api_key: 24eaf3714c1eca0d29698334fa96a65a5e259d04